schema_version: 1

context:
  name: "curve-apps"
  version: "0.0.0.dev0"  # This will be replaced by the actual version in the build process
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # url: https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz
  # sha256: d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed
  # curl -sL https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz | openssl sha256
  path: ../${{ name }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core >=1.8.0
    - poetry-dynamic-versioning >=1.9, <2.0.dev
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    # Mira packages
    - geoh5py >=0.12.0a, <0.13.dev
    - geoapps-utils >=0.6.0a, <0.7.dev
    # other direct dependencies
    - numpy >=1.26.0, <1.27.dev
    - pydantic >=2.5.2, <3.0.dev
    - scikit-image >=0.25.2, <0.26.dev
    - scipy >=1.14.0, <1.15.dev
    - tqdm >=4.66.1, <5.0.dev
    - dask >=2025.3, <2025.4.dev
    # Dash and related dependencies
    - dash >=3.0.4, 3.*
    - dash-bootstrap-components >=2.0.3, 2.*
    - dash-ag-grid >=32.3.1, <32.*
    - dash-daq 0.6.*
    - dash >=2.12.0, 2.*
    - dash-core-components >=3, 3.*
    - dash-html-components >=3, 3.*
    - dash-table 5.*
    - waitress >=3.0.2, 3.*

tests:
  - python:
      imports:
        - curve_apps
        - curve_apps._version
        - curve_apps.peak_finder
  - script:
      - pytest --ignore=tests/version_test.py
    requirements:
      run:
        - pytest
    files:
      source:
        - tests/

about:
  summary: Auto-detection of trends and edges in geoscientific data.
  description: |
    Auto-detection of trends and edges in geoscientific data.
    Includes the peak-finder application for the detection and grouping of time-domain
    electromagnetic (TEM) anomalies measured along flight lines.
  license: MIT
  license_file:
    - LICENSE
    - docs/source/THIRD_PARTY_SOFTWARE.rst
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/curve-apps
  documentation: https://mirageoscience-curve-apps.readthedocs-hosted.com/

extra:
  recipe-maintainers:
    - andrewg-mira
    - sebhmg
